### ISSUE TITLE
MissingET needs to be calculated after object selections if we use tighter object selection criteria than SUSYTools

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#11]
MET is calculated in CalibrateST, but we need to calculate it after our selections if we use a tighter hard object selection in our selection algs than SUSYTools.  It might be nicest to just overwrite it so the calculation alg can use the same name.

**Comment by lawrenceleejr** [comment]
Should we be using tighter object selections than what's given to SUSYTools? Like it might change per analysis, but the "signal" object selection shouldn't change per region for a given analysis I think, right? So I think it's more that CalibrateST needs to be configurable per analysis. i.e., should we just be configuring ST to do the harder selections - maybe we keep around ST config files in this package and point to them comme ça:

https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/SUSYPhys/SUSYTools/trunk/Root/SUSYObjDef_xAOD.cxx#L228

(Apologies if that's how it already works -- I'm going to actually start playing with the code now, so up to now I don't know much... :) )
