### ISSUE TITLE
Running Factory Tools code

### ISSUE THREAD

**Issue by marijamarjanovic** [rsmith54/RJigsawTools#118]
Hi,

I tried to install and run Factory Tools by following the instructions given in the README file, and after running the simple test as indicated in the README, I get a crash. [*] Sorry, I am new to this code, so probably the question is really naive, but I really need some help.
Thanks!

Cheers,
Marija

[*]
[mmarjano@lxplus055 FactoryTools_16_08_19]$ python FactoryTools/util/run_tls.py  --doOverwrite --nevents 10 --verbosity debug --inputDS /afs/cern.ch/work/r/rsmith/public/factoryToolsSample/

RestFrames v1.0.0 -- Developed by Christopher Rogan (crogan@cern.ch)
                     Copyright (c) 2014-2015, Christopher Rogan
                     http://RestFrames.com

xAOD::Init                INFO    Environment initialised for data access
INFO:root:creating new sample handler
INFO:root:creating new job
INFO:root:creating algorithms
BasicEventSelection::B... INFO    Calling constructor
INFO:root:adding basicEventSelection to algs
BasicEventSelection::s... INFO    Calling setupJob
INFO:root:adding calibrateST to algs
INFO:root:adding preselectTwoLepton to algs
INFO:root:adding selectTwoLepton to algs
INFO:root:adding postselectTwoLepton to algs
INFO:root:adding calculateRJigsawVariables to algs
INFO:root:adding calculateRegionVars to algs
INFO:root:adding writeOutputNtuple_SR to algs
INFO:root:Running 10 events
INFO:root:submit_dir already exists.
INFO:root:Overwriting previous submitDir
INFO:root:creating driver
INFO:root:direct driver
INFO:root:submit job
BasicEventSelection::B... INFO    Calling constructor
BasicEventSelection::B... INFO    Calling constructor
Running sample: mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.DAOD_SUSY1.e3698_s2608_s2183_r7725_r7676_p2596
BasicEventSelection::h... INFO    Calling histInitialize
BasicEventSelection::h... INFO    Histograms initialized!
BasicEventSelection::f... INFO    Calling fileExecute
BasicEventSelection::f... INFO    Incomplete cbk name: AllExecutedEvents - stream: StreamAOD 
BasicEventSelection::f... WARNING Found incomplete Bookkeepers from stream: StreamAOD ! Check input file for potential corruption...
BasicEventSelection::f... INFO    Looking at DAOD made by Derivation Algorithm: 
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamDAOD_SUSY1
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY4KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY4KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY3KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY3KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY10KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY10KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY8KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY8KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY1KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY1KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY2KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY2KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY6KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY6KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY12KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY12KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY5KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY5KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY11KernelAug - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: SUSY11KernelSkim - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamAOD
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamESD
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamRDO
BasicEventSelection::f... INFO    Complete cbk name: AllExecutedEvents - stream: StreamRDO
BasicEventSelection::f... ERROR   No CutBookkeeper corresponds to the selected Derivation Framework algorithm name. Check it with your DF experts! Aborting.
EventLoop:/build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/EventLoop/Root/Worker.cxx:46:exception: Algorithm::fileExecute returned StatusCode::FAILURE
worker finished:
Real time 0:00:02, CP time 2.420
Traceback (most recent call last):
  File "FactoryTools/util/run_tls.py", line 78, in <module>
    commonOptions.submitJob         ( job , options.driver , options.submitDir , options.gridUser , options.gridTag)
  File "/afs/cern.ch/work/m/mmarjano/0leptonRun2/FactoryTools_16_08_19/FactoryTools/util/commonOptions.py", line 94, in submitJob
    driver.submit(job, submitDir)
Exception: void EL::Driver::submit(const EL::Job& job, const string& location) =>
    EventLoop:/build2/atnight/localbuilds/nightlies/AnalysisBase-2.4.X/AnalysisBase/rel_nightly/EventLoop/Root/Worker.cxx:46:exception: Algorithm::fileExecute returned StatusCode::FAILURE (C++ exception)
xAOD::TFileAccessTracer   INFO    Sending file access statistics to http://rucio-lb-prod.cern.ch:18762/traces/
[mmarjano@lxplus055 FactoryTools_16_08_19]$

**Comment by rsmith54** [comment]
Hi @marijamarjanovic , 

Thanks for trying things out! I just updated the README to run the zl script by default.  Additionally, it should set the CBK object now, so this should be fixed. 

Let me know if you have any other issues or questions!

**Comment by marijamarjanovic** [comment]
Thanks so much!

Marija
