### ISSUE TITLE
Systematics 

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#28]
Just to remind myself we need to think about how to do systematics.  

I think it might be easiest to set this up from the run script and set the names of the output trees based on that.

**Comment by lawrenceleejr** [comment]
This doesn't look like it'll as simple as it looked. It would be great to just tack on some other algorithms but the way SUSYTools is set up it might be hard to do. See:

https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/SUSYPhys/SUSYAnalysisExample/trunk/Root/MyxAODAnalysis.cxx#L337

I'm trying to think of the best way. The ZL factory has a lot of machinery in place for this for adding a weight branch in the systematic just affects the overall weight, e.g. 

Also is there a way to incorporate this AthAnalysisBase alg into this rc setup somehow? Seems like the thing everyone would want/need..

https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/SUSYPhys/SUSYTools/trunk/src/SUSYToolsAlg.cxx

**Comment by rsmith54** [comment]
I think we can do the loop in the run script. I can try and set up the way
I was thinking sometime today.

**Comment by lawrenceleejr** [comment]
Yeah, so I think we can do that too, but there's two annoying things about that. 
1. SUSYTools has a nice feature where it can give you a list of all the possible systematics, and it would be nice to just loop over that list. But we'd be unable to if the loop is in the run script, right? (The function which creates the list requires SUSYTools to be initialized)
2. This is maybe non-optimal for systematics that lead to just a new weight? But maybe that's not a huge deal?

I'll be in r1 for much of the day probably so maybe we can "hack-a-thon" or "code jam" or whatever the kids are saying these days.

**Comment by rsmith54** [comment]
okay so everything is basically set up, but the systematics are not actually applied, so I need to figure out exactly why.

**Comment by rsmith54** [comment]
Things work now with the applySystematicVariation calling in the execute function.  The only problem is the setup relies on being able to set property from the python run script and also SystematicRegistry being available in python.  I have submitted an ASG JIRA ticket to get the SystematicRegistry added to the LinkDef (see link below).  This probably isn't strictly necessary though (we could access through ST indirectly)

The bigger deal is the SettingDataSource problem, since right now we need to set the DataSource from PyROOT to initialize SUSYTools.  I just sent an email about this so hopefully it can be changed or solvable with a new version of SUSYTools.

https://its.cern.ch/jira/browse/ATLASG-365?jql=project%20%3D%20ATLASG%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20PyROOT%20ORDER%20BY%20priority%20DESC

**Comment by rsmith54** [comment]
The other code has been updated enough, so we can do this finally. I'll add the code, update the readme and merge sometime today.

**Comment by rsmith54** [comment]
Completed by #64 and #65 .
