### ISSUE TITLE
Add preselection code

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#5]
We need a reasonable preselection in the SelectDileptonicWW events source file.

**Comment by rsmith54** [comment]
Thinking about it a bit, we should probably have another alg which does a preselection (but not necessarily selecting dilepton WW) and reserve this name for the SR selection algorithm.

**Comment by lawrenceleejr** [comment]
Sorry - Can you say what you mean more specifically? So we have a preselection alg (which does what kind of preselection. i.e. common to what regions) and then a separate for a proper SR?

The total output of this whole package should be at "preselection" level (at least defined in the same way as the 0L factory) right? So it seems like there still should just be for a given analysis N select functions. So like Select[AnalysisName][Region] as the name. SelectDileptonicWWSR, SelectDileptonicWWCR1L, etc, where each is to the preselection level.

Do you think that would work or do you have something else in mind that I'm missing?

**Comment by rsmith54** [comment]
I guess I was saying (poorly since I'm not exactly sure what I meant) that if some selection is the same between all of the regions it should be in a separate alg.  Something like the Meff and MET(') cuts from the factory.  Does that sound good?

(This also fits with the fact that I have the other algs separately listed).

**Comment by lawrenceleejr** [comment]
Oh I see. Yes ok. So should this actually be done at something like a post-selection level? Because e.g. let's say we wanted to cut on something like MET(') for all regions - The definition of MET(') is only set per region, right? (Think 0L CRY.) But on top of that, we may want to add an overall cut on an RJR variable instead. So this cut would have to be done after the calculateRJigsawVariables alg. So maybe we have a "selectDileptonicWWCommon" which is after the RJR calculation alg. Does that make sense?

**Comment by rsmith54** [comment]
Sorry for the slow response.  Yeah, I think something like that makes a lot of sense though.

**Comment by lawrenceleejr** [comment]
Cool. I was thinking about it the other day, and for things like cleaning, GRL, etc, we'd for sure want something common as well. But maybe that means we should have a pre selection and post selection algorithms? Not the best, but if we only had one, we would be doing unnecessary calculation for e.g. everything that's not in the GRL.

So maybe it should be like "preselectDileptonicWWCommon" and "postselectDileptonicWWCommon". Maybe I'll work on trying to port that kind of stuff over..

**Comment by rsmith54** [comment]
Yeah, that sounds great!

**Comment by lawrenceleejr** [comment]
Created in #20. Will keep open until a more mature preselection is implemented.

**Comment by lawrenceleejr** [comment]
GRL, Trigger, PRW, Bookkeeping, duplicate events are taken care of in the basic event selection algorithm provided by xAODAnaHelpers. Included in #23.

**Comment by lawrenceleejr** [comment]
And actually it takes care of event cleaning too.... We'll keep the preselection algorithm in case we come up with something we want to do with that... It that might be a useless alg in the end.

**Comment by lawrenceleejr** [comment]
MCVeto needs to go in here.

**Comment by lawrenceleejr** [comment]
MCVeto was actually added in a separate MCEventVeto alg. Done in #32.
