### ISSUE TITLE
Non-integer mu values 

### ISSUE THREAD

**Issue by joliver92** [rsmith54/RJigsawTools#50]
should these non-integer values be this way? 

![screen shot 2016-02-26 at 4 06 09 pm](https://cloud.githubusercontent.com/assets/17489193/13344150/4c9ed8d4-dca3-11e5-96da-9f80e2e0ac3e.png)

**Comment by rsmith54** [comment]
I just checked the default input file, and this is the same there.  I'm not sure this "should" be this way, but it's not a problem with RJigsawTools at least.

![image](https://cloud.githubusercontent.com/assets/8311342/13351442/f68d304c-dc86-11e5-87d0-1f081c202f7b.png)
![image](https://cloud.githubusercontent.com/assets/8311342/13351462/11047f7a-dc87-11e5-99ad-f8f0c467ecc4.png)
