### ISSUE TITLE
Two Lepton Strong Additions

### ISSUE THREAD

**Issue by lawrenceleejr** [rsmith54/RJigsawTools#52]
Things that need to be done...
- Make dev-Dylan compatible with master.  
- In the TLS region calculator, write out lepton signed PDGID as well. 
- Also add to the 2L calculator a variable isSS and isSF for ease of use later
- Write out a variable that encodes whether or not the leptons are in the same hemisphere

We want to try and run a production of these samples this weekend.

-L

**Comment by lawrenceleejr** [comment]
Also add compressed variables:
- Jet multiplicity in the S system
- Jet multiplicity in the ISR system
- Same for leptons
- dPhi variable calculated just one of the leptons (and then calculated with the other as well)

**Comment by dylanpeukert** [comment]
@lawrenceleejr I've added to my version the output for the PDGID, isSS and is SF.
I am still trying to get the variable of the number of leptons in the hemispheres working.

**Comment by rsmith54** [comment]
I updated the master to include the most recent code on dev-Dylan, so we should have PDGID, isSS and isSF in the master.

**Comment by lawrenceleejr** [comment]
Ok so current list is
- Write out a variable that encodes whether or not the leptons are in the same hemisphere
- Jet multiplicity in the S system
- Jet multiplicity in the ISR system
- Same for leptons
- dPhi variable calculated just one of the leptons (and then calculated with the other as well)

**Comment by dylanpeukert** [comment]
I pushed a new branch dev-Dylan2 which contains the same hemisphere variable and a fix to the passing of PDG ID to the RJigsaw calculator.

**Comment by lawrenceleejr** [comment]
Thanks @dylanpeukert! Various updates to 2L merged in #59. Will need to get crogan's input for dPhi variable.

**Comment by lawrenceleejr** [comment]
Additional variables pushed to a branch

93d667e5db62183250c7d0e5e7b968b159b39c79

waiting for additional changes to BasicEventSelection config and then rerunning over BG and signal on the grid with new variables. Closing issue.
