### ISSUE TITLE
Build some way to write out INTs to ntuple?

### ISSUE THREAD

**Issue by lawrenceleejr** [rsmith54/RJigsawTools#56]
We're wasting a lot of space now that we're starting to write out some ints and bools and storing them as doubles. Not sure if there's a clean way to do this, but it might be good to try and think of a way to make this more space-efficient.

**Comment by rsmith54** [comment]
Thinking about it a bit, this probably isn't worth it for now.  I'm going to close this but if we have problems with space we can reopen.
