### ISSUE TITLE
Algs for SR/CR/VRs 

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#6]
These should select the events based on whatever criteria we need in each of these regions, and then to fit in the framework we should do something like add a decoration to the EventInfo object (ala Sklimmer code).

**Comment by lawrenceleejr** [comment]
This has been done in the latest PR+merge:

https://github.com/rsmith54/RJigsawTools/pull/14

The decorator of type std::string and key "regionName" separates them. However, currently the single select algorithm takes care of all of the regions simultaneously, though I could be convinced that those need to be separated if there are strong feelings. 

Then based on this label, the WriteOutputNtuple alg will write out a new tree only if the decorator matches that instance of the algorithm.

Also added a super simple lepton selection to separate into the preselection trees "SR", "CR0L", and "CR1L". A la the ZeroLeptonRun2 factory, this should be the coarseness of these definitions - preselection. Full CR/SR/VR definitions will be done in HistFitter.
