### ISSUE TITLE
Error after compiling (newest version)

### ISSUE THREAD

**Issue by joliver92** [rsmith54/RJigsawTools#72]
Having an issue compiling properly, 

I follow the instructions and when I run the test example I get the following error:

TFile::TFile              ERROR   file /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/data/ElectronEfficiencyCorrection/efficiencySF.offline.TightLLH_d0z0_v10.2015.13TeV.rel20p0.25ns.v05.root does not exist
TAsgElectronEfficiency... ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/ElectronEfficiencyCorrection/Root/TElectronEfficiencyCorrectionTool.cxx:301 (virtual int Root::TElectronEfficiencyCorrectionTool::initialize()): TAsgElectronEfficiencyCorrectionTool_id_TightLLH (file: /build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/ElectronEfficiencyCorrection/Root/TElectronEfficiencyCorrectionTool.cxx, line: 301) ! No ROOT file found here: /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/data/ElectronEfficiencyCorrection/efficiencySF.offline.TightLLH_d0z0_v10.2015.13TeV.rel20p0.25ns.v05.root
AsgElectronEfficiencyC... ERROR   /build1/atnight/localbuilds/nightlies/AnalysisBase-2.3.X/AnalysisBase/rel_nightly/ElectronEfficiencyCorrection/Root/AsgElectronEfficiencyCorrectionTool.cxx:158 (virtual StatusCode AsgElectronEfficiencyCorrectionTool::initialize()): Could not initialize the TElectronEfficiencyCorrectionTool!
SUSYObjDef_xAOD           ERROR   /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/SUSYTools/Root/SUSYToolsInit.cxx:515 (StatusCode ST::SUSYObjDef_xAOD::SUSYToolsInit()): Failed to call "elecEfficiencySFTool_id->initialize()"
SUSYObjDef_xAOD           ERROR   /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/SUSYTools/Root/SUSYObjDef_xAOD.cxx:492 (virtual StatusCode ST::SUSYObjDef_xAOD::initialize()): Failed to call "this->SUSYToolsInit()"
virtual EL::StatusCode... ERROR   Failed to execute: "m_objTool->initialize()"

Any idea how to fix this / the origin of this error? 

Cheers, 

Jason

**Comment by lawrenceleejr** [comment]
Hi Jason

What analysis release do you have setup? It's in your util/setup.sh.

-L

**Comment by joliver92** [comment]
I have rcSetup Base,2.3.44 setup. I asked Dylan to try it out and he also gets the same errors

**Comment by lawrenceleejr** [comment]
Ok I'll give it a shot with a clean setup. Just to be clear - The way to check against the master is to first do a 

```
git checkout master
git pull
```

and then if the dependencies have changed, do an

```
rc clean
```

Then follow the instructions in the readme. Is there any part of that that you guys are missing by any chance?

@dylanpeukert 

-L

**Comment by lawrenceleejr** [comment]
Hi guys,

I see the same thing. I remember @rsmith54 and I discussing this issue - it has to do with the fact that we need to be using a newer version of SUSYTools than the release. 

@rsmith54 what did we do to fix this?

-L

**Comment by lawrenceleejr** [comment]
I see now that I have 45 setup. Can you try setting up Base,2.3.45 instead and running?

**Comment by lawrenceleejr** [comment]
Yeah that seems to work for me. I'll submit a PR.

**Comment by lawrenceleejr** [comment]
Done in #73

**Comment by lawrenceleejr** [comment]
Thanks for reporting this and sorry - your email got a bit lost in my inbox. Creating an issue on github is definitely the best way to get code things sorted. 

Cheers,
-L
