### ISSUE TITLE
xAODAnaHelpers not compiling

### ISSUE THREAD

**Issue by joliver92** [rsmith54/RJigsawTools#77]
Following the instructions again, this time with the rcSetup Base,2.3.45 version.

firstly, it tells me to change the root version to 6.04, which i do through the provided source 
I then 

rc find_packages 
rc compile 

and I get the following error at the end, 

At global scope:
cc1plus: warning: unrecognized command line option "-Wno-tautological-undefined-compare"
make: **\* [/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj/BasicEventSelection.o] Error 1
make: **\* Waiting for unfinished jobs....
RootCore: Error failed to compile package xAODAnaHelpers

I had this error last week during the non-stable release, is it possible its been re-introduced? 

Cheers, 

jason

**Comment by lawrenceleejr** [comment]
Can you send the full output? You've only shown a warning and not the error
that caused this to not compile. Find the first instance of the word error.

**Comment by joliver92** [comment]
sorry Larry, heres the full output from what I can tell at least: 

Cheers,

Jason

compiling xAODAnaHelpers
Making directory /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj
Making dependency for LinkDef.h
Making dependency for MuonSelector.cxx
Making dependency for OverlapRemover.cxx
Making dependency for DebugTool.cxx
Making dependency for ClusterHists.cxx
Making dependency for IParticleHists.cxx
Making dependency for TruthSelector.cxx
Making dependency for HLTJetGetter.cxx
Making dependency for HLTJetRoIBuilder.cxx
Making dependency for MuonHists.cxx
Making dependency for PhotonSelector.cxx
Making dependency for HelperFunctions.cxx
Making dependency for TauSelector.cxx
Making dependency for ElectronCalibrator.cxx
Making dependency for LinkDef.h
Making dependency for ElectronEfficiencyCorrector.cxx
Making dependency for JetHists.cxx
Making dependency for HistogramManager.cxx
Making dependency for IParticleHistsAlgo.cxx
Making dependency for PhotonCalibrator.cxx
Making dependency for TracksInJetHists.cxx
Making dependency for MuonCalibrator.cxx
Making dependency for METConstructor.cxx
Making dependency for Algorithm.cxx
Making dependency for TrackHistsAlgo.cxx
Making dependency for JetHistsAlgo.cxx
Making dependency for Writer.cxx
Making dependency for ClusterHistsAlgo.cxx
Making dependency for PhotonHistsAlgo.cxx
Making dependency for MuonEfficiencyCorrector.cxx
Making dependency for HelperClasses.cxx
Making dependency for MetHists.cxx
Making dependency for TrackSelector.cxx
Making dependency for VtxHists.cxx
Making dependency for TrackHists.cxx
Making dependency for MetHistsAlgo.cxx
Making dependency for ElectronSelector.cxx
Making dependency for MinixAOD.cxx
Making dependency for HelpTreeBase.cxx
Making dependency for JetCalibrator.cxx
Making dependency for BJetEfficiencyCorrector.cxx
Making dependency for TreeAlgo.cxx
Making dependency for MuonHistsAlgo.cxx
Making dependency for PhotonHists.cxx
Making dependency for BasicEventSelection.cxx
Making dependency for JetSelector.cxx
Compiling BJetEfficiencyCorrector.o
Compiling Algorithm.o
Compiling ClusterHistsAlgo.o
Compiling ElectronCalibrator.o
Compiling BasicEventSelection.o
Compiling ClusterHists.o
Compiling DebugTool.o
Compiling ElectronEfficiencyCorrector.o
Compiling ElectronSelector.o
Compiling HLTJetGetter.o
Compiling HLTJetRoIBuilder.o
Compiling HelpTreeBase.o
Compiling HelperClasses.o
Compiling HelperFunctions.o
Compiling HistogramManager.o
Compiling IParticleHists.o
/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx: In member function ‘virtual EL::StatusCode BasicEventSelection::execute()’:
/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:600:39: error: no matching function for call to ‘CP::PileupReweightingTool::apply(const EventInfo&)’
       m_pileuptool->apply( _eventInfo ); // NB: this call automatically decorates eventInfo with:
                                       ^
/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:600:39: note: candidate is:
In file included from /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/xAODAnaHelpers/BasicEventSelection.h:9:0,
                 from /afs/cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:29:
/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/include/PileupReweighting/PileupReweightingTool.h:87:26: note: virtual StatusCode CP::PileupReweightingTool::apply(const EventInfo&, bool)
       virtual StatusCode apply ( const xAOD::EventInfo& eventInfo, bool mu_dependent );
                          ^
/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/include/PileupReweighting/PileupReweightingTool.h:87:26: note:   candidate expects 2 arguments, 1 provided
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-tautological-undefined-compare"
make: *_\* [/afs/cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj/BasicEventSelection.o] Error 1
make: **\* Waiting for unfinished jobs....
RootCore: Error failed to compile package xAODAnaHelpers

**Comment by lawrenceleejr** [comment]
Ok thanks. I'll write a patch. It's weird that that no longer comes up for
me when I do a fresh install. Give me a few minutes. Sorry about that!
On Tue, Mar 15, 2016 at 8:01 AM JOliver-GH notifications@github.com wrote:

> sorry Larry, heres the full output from what I can tell at least:
> 
> Cheers,
> 
> Jason
> 
> compiling xAODAnaHelpers
> Making directory /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj
> Making dependency for LinkDef.h
> Making dependency for MuonSelector.cxx
> Making dependency for OverlapRemover.cxx
> Making dependency for DebugTool.cxx
> Making dependency for ClusterHists.cxx
> Making dependency for IParticleHists.cxx
> Making dependency for TruthSelector.cxx
> Making dependency for HLTJetGetter.cxx
> Making dependency for HLTJetRoIBuilder.cxx
> Making dependency for MuonHists.cxx
> Making dependency for PhotonSelector.cxx
> Making dependency for HelperFunctions.cxx
> Making dependency for TauSelector.cxx
> Making dependency for ElectronCalibrator.cxx
> Making dependency for LinkDef.h
> Making dependency for ElectronEfficiencyCorrector.cxx
> Making dependency for JetHists.cxx
> Making dependency for HistogramManager.cxx
> Making dependency for IParticleHistsAlgo.cxx
> Making dependency for PhotonCalibrator.cxx
> Making dependency for TracksInJetHists.cxx
> Making dependency for MuonCalibrator.cxx
> Making dependency for METConstructor.cxx
> Making dependency for Algorithm.cxx
> Making dependency for TrackHistsAlgo.cxx
> Making dependency for JetHistsAlgo.cxx
> Making dependency for Writer.cxx
> Making dependency for ClusterHistsAlgo.cxx
> Making dependency for PhotonHistsAlgo.cxx
> Making dependency for MuonEfficiencyCorrector.cxx
> Making dependency for HelperClasses.cxx
> Making dependency for MetHists.cxx
> Making dependency for TrackSelector.cxx
> Making dependency for VtxHists.cxx
> Making dependency for TrackHists.cxx
> Making dependency for MetHistsAlgo.cxx
> Making dependency for ElectronSelector.cxx
> Making dependency for MinixAOD.cxx
> Making dependency for HelpTreeBase.cxx
> Making dependency for JetCalibrator.cxx
> Making dependency for BJetEfficiencyCorrector.cxx
> Making dependency for TreeAlgo.cxx
> Making dependency for MuonHistsAlgo.cxx
> Making dependency for PhotonHists.cxx
> Making dependency for BasicEventSelection.cxx
> Making dependency for JetSelector.cxx
> Compiling BJetEfficiencyCorrector.o
> Compiling Algorithm.o
> Compiling ClusterHistsAlgo.o
> Compiling ElectronCalibrator.o
> Compiling BasicEventSelection.o
> Compiling ClusterHists.o
> Compiling DebugTool.o
> Compiling ElectronEfficiencyCorrector.o
> Compiling ElectronSelector.o
> Compiling HLTJetGetter.o
> Compiling HLTJetRoIBuilder.o
> Compiling HelpTreeBase.o
> Compiling HelperClasses.o
> Compiling HelperFunctions.o
> Compiling HistogramManager.o
> Compiling IParticleHists.o
> /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:
> In member function ‘virtual EL::StatusCode BasicEventSelection::execute()’:
> /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:600:39:
> error: no matching function for call to
> ‘CP::PileupReweightingTool::apply(const EventInfo&)’
> m_pileuptool->apply( _eventInfo ); // NB: this call automatically
> decorates eventInfo with:
> ^
> /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:600:39:
> note: candidate is:
> In file included from /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/xAODAnaHelpers/BasicEventSelection.h:9:0
> ,
> from /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/xAODAnaHelpers/Root/BasicEventSelection.cxx:29
> :
> /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/include/PileupReweighting/PileupReweightingTool.h:87:26:
> note: virtual StatusCode CP::PileupReweightingTool::apply(const EventInfo&,
> bool)
> virtual StatusCode apply ( const xAOD::EventInfo& eventInfo, bool
> mu_dependent );
> ^
> /afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/include/PileupReweighting/PileupReweightingTool.h:87:26:
> note: candidate expects 2 arguments, 1 provided
> At global scope:
> cc1plus: warning: unrecognized command line option
> "-Wno-tautological-undefined-compare"
> make: *_\* [/afs/
> cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj/BasicEventSelection.o]
> Error 1
> make: **\* Waiting for unfinished jobs....
> RootCore: Error failed to compile package xAODAnaHelpers
> 
> > On 15 Mar 2016, at 4:27 PM, Lawrence Lee notifications@github.com
> > wrote:
> > 
> > Can you send the full output? You've only shown a warning and not the
> > error
> > that caused this to not compile. Find the first instance of the word
> > error.
> > On Tue, Mar 15, 2016 at 4:57 AM JOliver-GH notifications@github.com
> > wrote:
> > 
> > > Following the instructions again, this time with the rcSetup
> > > Base,2.3.45
> > > version.
> > > 
> > > firstly, it tells me to change the root version to 6.04, which i do
> > > through the provided source
> > > I then
> > > 
> > > rc find_packages
> > > rc compile
> > > 
> > > and I get the following error at the end,
> > > 
> > > At global scope:
> > > cc1plus: warning: unrecognized command line option
> > > "-Wno-tautological-undefined-compare"
> > > make: **\* [/afs/
> > > 
> > > cern.ch/work/j/jaoliver/private/RJigsawTools/RootCoreBin/obj/x86_64-slc6-gcc49-opt/xAODAnaHelpers/obj/BasicEventSelection.o
> > > ]
> > > Error 1
> > > make: **\* Waiting for unfinished jobs....
> > > RootCore: Error failed to compile package xAODAnaHelpers
> > > 
> > > I had this error last week during the non-stable release, is it
> > > possible
> > > its been re-introduced?
> > > 
> > > Cheers,
> > > 
> > > jason
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/rsmith54/RJigsawTools/issues/77
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/rsmith54/RJigsawTools/issues/77#issuecomment-196676896
> > <https://github.com/rsmith54/RJigsawTools/issues/77#issuecomment-196676896
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/rsmith54/RJigsawTools/issues/77#issuecomment-196690674
> 
> ## 

-L

Sent from my iPhone

**Comment by lawrenceleejr** [comment]
@JOliver-GH do a git pull and try to apply the patch that's in the readme?

It's the only change, so you should be able to go into the XAH directory and apply the patch as in the new readme - should fix it.
