### ISSUE TITLE
--driver grid prompt

### ISSUE THREAD

**Issue by joliver92** [rsmith54/RJigsawTools#80]
Just letting you know that when you run 

python RJigsawTools/util/run_lvlv.py  --doOverwrite --inputDS RJigsawTools/data/mc15_13TeV_HIGG3D1_TEST.ds --gridTag 012516_lvlv 

It no longer prompts you asking "did you mean to include --driver grid", rather it runs it on lxplus. Not sure if this is intentional, but i found the prompt to be helpful 

python RJigsawTools/util/run_lvlv.py  --doOverwrite --inputDS RJigsawTools/data/mc15_13TeV_HIGG3D1_TEST.ds --gridTag 012516_lvlv --driver grid 

is what I run for the grid, as usual

**Comment by rsmith54** [comment]
This should fix it.  Let me know if you have any other changes you want!
