### ISSUE TITLE
Move general vars that every analysis to a common area.

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#82]
Testing #80 changes I had the old issue where mcEventWeight was being retrieved as an int still, even though we fixed this since I was running the _zl code where it wasn't fixed.  

To avoid similar things in the future, it would be good if we could move the things that _every_ analysis needs to a common place (EventNumber, RunNumber, mcEventWeight etc... ).

**Comment by rsmith54** [comment]
I think most (all?) of these types of variables come from the EventInfo object, so I'm going to make a function which just takes a reference to that pointer and then retrieves those that we now have in RegionVarCalculator_*.

**Comment by rsmith54** [comment]
Leaving open in case @lawrenceleejr or others think we should maybe add some additional things to the general calculation function.

**Comment by lawrenceleejr** [comment]
I'm going to close this after slight addition implemented in #90
