### ISSUE TITLE
Investigate crazy high value events

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#86]
Some events seem to have very high (>1e9 GeV)  for example for H2PP, but the bulk seem fine.  Gotta investigate these events...

**Comment by rsmith54** [comment]
running 

`python run_tls.py  --doOverwrite --nevents 10000 --inputDS mc15_13TeV.361414.Sherpa_CT10_Zmumu_Pt1000_2000_CVetoBVeto.merge.DAOD_SUSY1.e4133_s2608_s2183_r6869_r6282_p2419`

let's me reproduce this with manageable sample.  It seems to happen in a small fraction of events.  I'm hoping (maybe against hope) that this is something with the very large values / floats/ doubles but we'll see....

**Comment by rsmith54** [comment]
This happens when there is 1 Jet in the Jets container (and 1 or 2 Leptons).  Investigating further.

**Comment by lawrenceleejr** [comment]
As @rsmith54 found out, this appears to be negative mass leptons in our xAOD::Particle objects. They are fine in the original containers. Something is screwy with the ::p4() and ::setp4() functions somewhere....

**Comment by rsmith54** [comment]
Finally fixed with #93.  We have moved to using a nicer IParticleContainer setup as well which is safer and faster than the previous particle copying.
