### ISSUE TITLE
How do we have have the same lepPt in hte next event?

### ISSUE THREAD

**Issue by rsmith54** [rsmith54/RJigsawTools#88]
![image](https://cloud.githubusercontent.com/assets/8311342/13955942/faca78b2-f046-11e5-9e80-8925762d96ef.png)

**Comment by rsmith54** [comment]
confirmed not seen in the SUSY1 Wenu CVetoBVeto Pt0_70 slice, but the merged sample where this is seen is actually the SUSY2 version.  Rerunning on that directly now.

**Comment by rsmith54** [comment]
Okay, so I am relatively confident this is fixed or not a bug with the framework.  Running over the entire SUSY2 Wenu CVetoBVeto Pt0_70 slice, I don't see this effect in any of the events passing the two lepton selection as above (in the wjets.root).  This is where it is seen in the file above, so the fact that we don't see it at all means the only thing left to check is the merging. Otherwise, we should be good.

![image](https://cloud.githubusercontent.com/assets/8311342/14118139/5c499806-f5e8-11e5-84b3-6a0f023b2a8d.png)

**Comment by lawrenceleejr** [comment]
Can you put the output files somewhere public so I can try a single-file merge?

**Comment by rsmith54** [comment]
Yeah, for sure. On my way to CERN now so I'll do it as soon as I arrive.

**Comment by rsmith54** [comment]
Okay, checked that it doesn't happen when merging the output with itself.  Obviously we need to keep track of this for the future, but I'm closing for now.

![Uploading image.png…]()

**Comment by rsmith54** [comment]
![image](https://cloud.githubusercontent.com/assets/8311342/14137032/2fe3576a-f666-11e5-9050-f6cbb1b89867.png)
